version: "3.9"
services:
  clickhouse:
    image: clickhouse/clickhouse-server:24.3
    container_name: dq-clickhouse
    ports:
      - "8125:8123"
      - "9002:9000"
    environment:
      CLICKHOUSE_DB: dq
      CLICKHOUSE_USER: default
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: "1"
    volumes:
      - dq_clickhouse_data:/var/lib/clickhouse
      - dq_clickhouse_logs:/var/log/clickhouse-server

  redpanda:
    image: docker.redpanda.com/redpandadata/redpanda:v23.3.10
    container_name: dq-redpanda
    command:
      - redpanda
      - start
      - --smp
      - "1"
      - --reserve-memory
      - 0M
      - --overprovisioned
      - --node-id
      - "0"
      - --kafka-addr
      - PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:39092
      - --advertise-kafka-addr
      - PLAINTEXT://dq-redpanda:29092,OUTSIDE://localhost:39092
    ports:
      - "39092:39092"

  akhq:
    image: tchiotludo/akhq:latest
    container_name: dq-akhq
    ports:
      - "8089:8080"
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          connections:
            redpanda:
              properties:
                bootstrap.servers: "dq-redpanda:29092"
          server:
            access-log:
              enabled: true
    depends_on:
      - redpanda

  prometheus:
    image: prom/prometheus:latest
    container_name: dq-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - dq_prometheus_data:/prometheus
    depends_on:
      - clickhouse
      - redpanda

volumes:
  dq_clickhouse_data:
  dq_clickhouse_logs:
  dq_prometheus_data:
