clickhouse:
  host: localhost
  port: 8125
  database: dq
  username: default
  password: ""

kafka:
  bootstrap_servers: localhost:39092
  topic:
    partitions: 1
    replication_factor: 1
    create_timeout_seconds: 10
    delete_timeout_seconds: 30

  consumer:
    default_timeout_seconds: 0.8

  producer_profiles:
    high_throughput:
      linger_ms: 100
      batch_size: 1000000
      compression_type: "snappy"
      acks: 1
      max_in_flight: 10
      queue_buffering_max_messages: 100000
      queue_buffering_max_kbytes: 1048576
    low_latency:
      linger_ms: 0
      batch_size: 16384
      compression_type: "snappy"
      acks: 1
      max_in_flight: 5
      queue_buffering_max_messages: 100000
      queue_buffering_max_kbytes: 1048576
    reliable:
      linger_ms: 100
      batch_size: 1000000
      compression_type: "snappy"
      acks: -1
      max_in_flight: 1
      queue_buffering_max_messages: 100000
      queue_buffering_max_kbytes: 1048576
